---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-12.04
  - name: ubuntu-14.04
#  - name: centos-6.5

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[hadoop::install]
      - recipe[spark::install]
      - recipe[zeppelin::install]
      - recipe[hadoop::nn]
      - recipe[hadoop::dn]
      - recipe[spark::master]
      - recipe[spark::slave]
      - recipe[zeppelin::default]
    attributes:
         hadoop:
            user: glassfish
            nn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
#            native_libraries: "true"
         spark:
            master:
               private_ips: ["10.0.2.15"]
            slave:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         zeppelin:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
