---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-6.5

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[hops::install]
      - recipe[hopsworks::install]
      - recipe[spark::install]
      - recipe[zeppelin::install]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[ndb::memcached]
      - recipe[hops::ndb]
      - recipe[hops::nn]
      - recipe[hops::dn]
      - recipe[hops::rm]
      - recipe[hops::nm]
      - recipe[hops::jhs]
      - recipe[hopsworks]
      - recipe[spark::master]
      - recipe[spark::slave]
      - recipe[zeppelin::default]
    attributes:
         vagrant: "true"
         authorization:
            sudo:
              users: ['vagrant']
              passwordless: true
              include_sudoers_d: true
         hopsworks:
            default:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         ndb:
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
            memcached:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            enabled: "true"
         hops:
            user: glassfish
            nn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
         hdfs:
            user: glassfish
         hadoop:
            yarn: 
               user: glassfish
            mr: 
               user: glassfish
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
#            user_envs: "false"
         spark:
            master:
               private_ips: ["10.0.2.15"]
            slave:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         zeppelin:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
